// <auto-generated />
using GoldenGrill.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoldenGrill.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.14");

            modelBuilder.Entity("GoldenGrill.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Double smash patty, cheddar, pickles, mustard",
                            ImageUrl = "/images/classic-smash.jpg",
                            Name = "Classic Smash",
                            Price = 29.90m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Crispy bacon, BBQ sauce, onion rings, cheddar",
                            ImageUrl = "/images/bbq-bacon-crunch.jpg",
                            Name = "BBQ Bacon Crunch",
                            Price = 34.90m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Jalapeños, pepper jack, chipotle mayo, lettuce",
                            ImageUrl = "/images/spicy-jalapeno.jpg",
                            Name = "Spicy Jalapeño",
                            Price = 31.90m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
